# Generated by Django 5.1.5 on 2026-01-11 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0002_user_bio_user_followers_user_profile_picture_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="user_name",
            field=models.CharField(blank=True, max_length=63, null=True),
        ),
    ]
